
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class PostWidget
	{
		private global::Gtk.EventBox mainBox;
		
		private global::Gtk.VBox vLayoutBox;
		
		private global::Gtk.EventBox headerBox;
		
		private global::Gtk.Fixed headerContainer;
		
		private global::Gtk.Label titleLabel;
		
		private global::Gtk.Label timeLabel;
		
		private global::Gtk.EventBox bodyBox;
		
		private global::Gtk.Fixed bodyContainer;
		
		private global::Gtk.Label bodyMarkup;
		
		private global::Gtk.Label authorLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.PostWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.PostWidget";
			// Container child CodeWalriiNotify.PostWidget.Gtk.Container+ContainerChild
			this.mainBox = new global::Gtk.EventBox ();
			this.mainBox.Name = "mainBox";
			// Container child mainBox.Gtk.Container+ContainerChild
			this.vLayoutBox = new global::Gtk.VBox ();
			this.vLayoutBox.Name = "vLayoutBox";
			this.vLayoutBox.Spacing = 6;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.headerBox = new global::Gtk.EventBox ();
			this.headerBox.Name = "headerBox";
			// Container child headerBox.Gtk.Container+ContainerChild
			this.headerContainer = new global::Gtk.Fixed ();
			this.headerContainer.WidthRequest = 450;
			this.headerContainer.HeightRequest = 75;
			this.headerContainer.Name = "headerContainer";
			this.headerContainer.HasWindow = false;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.titleLabel = new global::Gtk.Label ();
			this.titleLabel.WidthRequest = 300;
			this.titleLabel.HeightRequest = 30;
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.Xalign = 0F;
			this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.titleLabel.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.headerContainer.Add (this.titleLabel);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.titleLabel]));
			w1.X = 9;
			w1.Y = 7;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.timeLabel = new global::Gtk.Label ();
			this.timeLabel.WidthRequest = 200;
			this.timeLabel.HeightRequest = 15;
			this.timeLabel.Name = "timeLabel";
			this.timeLabel.Xalign = 1F;
			this.timeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Time");
			this.headerContainer.Add (this.timeLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.timeLabel]));
			w2.X = 244;
			w2.Y = 53;
			this.headerBox.Add (this.headerContainer);
			this.vLayoutBox.Add (this.headerBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.headerBox]));
			w4.Position = 0;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.bodyBox = new global::Gtk.EventBox ();
			this.bodyBox.Name = "bodyBox";
			// Container child bodyBox.Gtk.Container+ContainerChild
			this.bodyContainer = new global::Gtk.Fixed ();
			this.bodyContainer.WidthRequest = 200;
			this.bodyContainer.HeightRequest = 200;
			this.bodyContainer.Name = "bodyContainer";
			this.bodyContainer.HasWindow = false;
			// Container child bodyContainer.Gtk.Fixed+FixedChild
			this.bodyMarkup = new global::Gtk.Label ();
			this.bodyMarkup.WidthRequest = 430;
			this.bodyMarkup.HeightRequest = 150;
			this.bodyMarkup.Name = "bodyMarkup";
			this.bodyMarkup.Xalign = 0F;
			this.bodyMarkup.Yalign = 0F;
			this.bodyMarkup.LabelProp = global::Mono.Unix.Catalog.GetString ("BodyMarkup");
			this.bodyMarkup.UseMarkup = true;
			this.bodyMarkup.Wrap = true;
			this.bodyContainer.Add (this.bodyMarkup);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.bodyContainer [this.bodyMarkup]));
			w5.X = 10;
			w5.Y = 11;
			// Container child bodyContainer.Gtk.Fixed+FixedChild
			this.authorLabel = new global::Gtk.Label ();
			this.authorLabel.WidthRequest = 200;
			this.authorLabel.HeightRequest = 15;
			this.authorLabel.Name = "authorLabel";
			this.authorLabel.Xalign = 1F;
			this.authorLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Author");
			this.bodyContainer.Add (this.authorLabel);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.bodyContainer [this.authorLabel]));
			w6.X = 244;
			w6.Y = 175;
			this.bodyBox.Add (this.bodyContainer);
			this.vLayoutBox.Add (this.bodyBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.bodyBox]));
			w8.Position = 1;
			this.mainBox.Add (this.vLayoutBox);
			this.Add (this.mainBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
