
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class PostWidget
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Fixed headerContainer;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Fixed lowerContainer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.PostWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.PostWidget";
			// Container child CodeWalriiNotify.PostWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.headerContainer = new global::Gtk.Fixed ();
			this.headerContainer.WidthRequest = 100;
			this.headerContainer.HeightRequest = 75;
			this.headerContainer.Name = "headerContainer";
			this.headerContainer.HasWindow = false;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.headerContainer.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.label2]));
			w1.X = 82;
			w1.Y = 20;
			this.vbox2.Add (this.headerContainer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.headerContainer]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lowerContainer = new global::Gtk.Fixed ();
			this.lowerContainer.WidthRequest = 200;
			this.lowerContainer.HeightRequest = 200;
			this.lowerContainer.Name = "lowerContainer";
			this.lowerContainer.HasWindow = false;
			this.vbox2.Add (this.lowerContainer);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lowerContainer]));
			w3.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
