
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class BBCodeViewer
	{
		private global::Gtk.Image Canvas;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.BBCodeViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.BBCodeViewer";
			// Container child CodeWalriiNotify.BBCodeViewer.Gtk.Container+ContainerChild
			this.Canvas = new global::Gtk.Image ();
			this.Canvas.Name = "Canvas";
			this.Add (this.Canvas);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
