
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class RecyclerView
	{
		private global::Gtk.ScrolledWindow ScrollView;
		
		private global::Gtk.VBox ContainerView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.RecyclerView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.RecyclerView";
			// Container child CodeWalriiNotify.RecyclerView.Gtk.Container+ContainerChild
			this.ScrollView = new global::Gtk.ScrolledWindow ();
			this.ScrollView.CanFocus = true;
			this.ScrollView.Name = "ScrollView";
			this.ScrollView.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.ScrollView.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.ScrollView.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ScrollView.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.ContainerView = new global::Gtk.VBox ();
			this.ContainerView.Name = "ContainerView";
			this.ContainerView.Spacing = 6;
			w1.Add (this.ContainerView);
			this.ScrollView.Add (w1);
			this.Add (this.ScrollView);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
