
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class SettingsDialog
	{
		private global::Gtk.Notebook tabControl;
		
		private global::Gtk.ScrolledWindow generalScroll;
		
		private global::Gtk.VBox generalWrapperVbox;
		
		private global::Gtk.VBox generalFeedActionsVbox;
		
		private global::Gtk.Label feedActionsLbl;
		
		private global::Gtk.HButtonBox feedActionBtnBox;
		
		private global::Gtk.Button generalLoadDefaults;
		
		private global::Gtk.Fixed generalSpacer1;
		
		private global::Gtk.Table generalTable;
		
		private global::Gtk.Label applicationSettingsLbl;
		
		private global::Gtk.CheckButton customIconCb;
		
		private global::Gtk.Label customIconCbLbl;
		
		private global::Gtk.Label feedSettingsLbl;
		
		private global::Gtk.Entry feedTitleTxt;
		
		private global::Gtk.Label feedUrlTxLbl;
		
		private global::Gtk.Entry feedUrlTxt;
		
		private global::Gtk.Fixed generalSpacer2;
		
		private global::Gtk.Fixed generalSpacer3;
		
		private global::Gtk.FileChooserButton iconFileSel;
		
		private global::Gtk.Label iconFileSelLbl;
		
		private global::Gtk.Label maxPostsDcLbl;
		
		private global::Gtk.SpinButton maxPostsDec;
		
		private global::Gtk.Label queryIntervalDcLbl;
		
		private global::Gtk.SpinButton queryIntervalDec;
		
		private global::Gtk.Label querySettingsLbl;
		
		private global::Gtk.Label serverNameTxLbl;
		
		private global::Gtk.Label generalSettingsLbl;
		
		private global::Gtk.ScrolledWindow notificationScroll;
		
		private global::Gtk.VBox notificationsWrapperVbox;
		
		private global::Gtk.VBox notificationsActionsVbox;
		
		private global::Gtk.Label notificationActionsLbl;
		
		private global::Gtk.HButtonBox notificationActionBtnBox;
		
		private global::Gtk.Button notificationLoadDefaultsBtn;
		
		private global::Gtk.Fixed notificationSpacer;
		
		private global::Gtk.Table notificationTable;
		
		private global::Gtk.Label audioNotificationsLbl;
		
		private global::Gtk.CheckButton audioNotifyCustomAudioCb;
		
		private global::Gtk.Label audioNotifyCustomAudioCbLbl;
		
		private global::Gtk.CheckButton audioNotifyEnabledCb;
		
		private global::Gtk.Label audioNotifyEnabledCbLbl;
		
		private global::Gtk.FileChooserButton audioNotifyFileSel;
		
		private global::Gtk.Label audioNotifyFileSelLbl;
		
		private global::Gtk.Fixed notificationSpacer1;
		
		private global::Gtk.Fixed notificationSpacer2;
		
		private global::Gtk.Label taskbarIconCounterPositionLbl;
		
		private global::Gtk.Label taskbarIconEnableUnreadLbl;
		
		private global::Gtk.Label taskbarIconLbl;
		
		private global::Gtk.CheckButton taskbarIconUnreadEnabledCb;
		
		private global::Gtk.ComboBox taskbarIconUnreadPositionCbx;
		
		private global::Gtk.Label visualNotificationsLbl;
		
		private global::Gtk.CheckButton visualNotifyAnimationCb;
		
		private global::Gtk.Label visualNotifyAnimationCbLbl;
		
		private global::Gtk.SpinButton visualNotifyAnimationIntervalDec;
		
		private global::Gtk.Label visualNotifyAnimationIntervalDecLbl;
		
		private global::Gtk.CheckButton visualNotifyEnabledCb;
		
		private global::Gtk.Label visualNotifyEnabledCbLbl;
		
		private global::Gtk.SpinButton visualNotifyTimeoutDec;
		
		private global::Gtk.Label visualNotifyTimeoutDecLbl;
		
		private global::Gtk.HScale visualNotifyVerticalAlignmentSlide;
		
		private global::Gtk.Label visualNotifyVerticalAlignmentSlideLbl;
		
		private global::Gtk.Label notificationSettingsLbl;
		
		private global::Gtk.ScrolledWindow contentScroll;
		
		private global::Gtk.VBox contentWrapperVbox;
		
		private global::Gtk.VBox contentActionsVbox;
		
		private global::Gtk.Label contentActionsLbl;
		
		private global::Gtk.HButtonBox contentActionBtnBox;
		
		private global::Gtk.Button contentLoadDefaultsBtn;
		
		private global::Gtk.Fixed contentSpacer1;
		
		private global::Gtk.Table contentTable;
		
		private global::Gtk.Fixed contentSpacer2;
		
		private global::Gtk.Fixed contentSpacer3;
		
		private global::Gtk.Fixed contentSpacer4;
		
		private global::Gtk.Fixed contentSpacer5;
		
		private global::Gtk.Label displaySettingsLbl;
		
		private global::Gtk.CheckButton hideIgnoredPostsCb;
		
		private global::Gtk.Label hideIgnoredPostsCbLbl;
		
		private global::Gtk.Label ignoredPostsLbl;
		
		private global::Gtk.Label ignoredTopicsLbl;
		
		private global::Gtk.Label ignoredUsersLbl;
		
		private global::Gtk.HButtonBox ignTopicsBtnBox;
		
		private global::Gtk.Button ignTopicAddBtn;
		
		private global::Gtk.Button ignTopicsRemoveBtn;
		
		private global::Gtk.ComboBoxEntry ignTopicsComboEntry;
		
		private global::Gtk.HButtonBox ignUsersBtnBox;
		
		private global::Gtk.Button ignUsersAddBtn;
		
		private global::Gtk.Button ignUsersRemoveBtn;
		
		private global::Gtk.ComboBoxEntry ignUsersComboEntry;
		
		private global::Gtk.Label minWordcountDecLbl;
		
		private global::Gtk.SpinButton minWordsDec;
		
		private global::Gtk.Label syntaxInfoLbl;
		
		private global::Gtk.Label syntaxInfoLblLbl;
		
		private global::Gtk.Label contentScrollLbl;
		
		private global::Gtk.ScrolledWindow styleScroll;
		
		private global::Gtk.VBox styleWrapperVbox;
		
		private global::Gtk.VBox styleActionsVbox;
		
		private global::Gtk.Label styleActionsLbl;
		
		private global::Gtk.HButtonBox hbuttonbox2;
		
		private global::Gtk.Button stylesLoadDefaultsBtn;
		
		private global::Gtk.Fixed styleSpacer1;
		
		private global::Gtk.Table styleTable;
		
		private global::Gtk.Label authorFgClLbl;
		
		private global::Gtk.ColorButton authorFgColorBtn;
		
		private global::Gtk.CheckButton bodyAntiAliasCb;
		
		private global::Gtk.Label bodyAntiAliasCbLbl;
		
		private global::Gtk.Label bodyBgClLbl;
		
		private global::Gtk.ColorButton bodyBgColorBtn;
		
		private global::Gtk.ScrolledWindow bodyFormatScroll;
		
		private global::Gtk.TextView bodyFormatTxt;
		
		private global::Gtk.Label bodyFormatTxLbl;
		
		private global::Gtk.Label colorsLbl;
		
		private global::Gtk.Label detailFnLbl;
		
		private global::Gtk.FontButton detailFontBtn;
		
		private global::Gtk.Label footerBgClLbl;
		
		private global::Gtk.ColorButton footerBgColorBtn;
		
		private global::Gtk.Label headerBgClLbl;
		
		private global::Gtk.ColorButton headerBgColorBtn;
		
		private global::Gtk.ColorButton iconBgColorBtn;
		
		private global::Gtk.Label iconBgColorLbl;
		
		private global::Gtk.ColorButton iconFgColorBtn;
		
		private global::Gtk.Label iconFgColorLbl;
		
		private global::Gtk.FontButton iconFontBtn;
		
		private global::Gtk.Label iconLbl;
		
		private global::Gtk.Fixed styleSpacer2;
		
		private global::Gtk.Label textLbl;
		
		private global::Gtk.Label timeFgClLbl;
		
		private global::Gtk.ColorButton timeFgColorBtn;
		
		private global::Gtk.Label titleFgClLbl;
		
		private global::Gtk.ColorButton titleFgColorBtn;
		
		private global::Gtk.Label titleFnLbl;
		
		private global::Gtk.FontButton titleFontBtn;
		
		private global::Gtk.Label styleSettingsLbl;
		
		private global::Gtk.Button okButton;
		
		private global::Gtk.Button cancelButton;
		
		private global::Gtk.Button defaultsButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.SettingsDialog
			this.Name = "CodeWalriiNotify.SettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Settings");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Dnd);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child CodeWalriiNotify.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialogVbox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialogVbox.Gtk.Box+BoxChild
			this.tabControl = new global::Gtk.Notebook ();
			this.tabControl.CanFocus = true;
			this.tabControl.Name = "tabControl";
			this.tabControl.CurrentPage = 2;
			// Container child tabControl.Gtk.Notebook+NotebookChild
			this.generalScroll = new global::Gtk.ScrolledWindow ();
			this.generalScroll.CanFocus = true;
			this.generalScroll.Name = "generalScroll";
			this.generalScroll.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.generalScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.generalScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child generalScroll.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.generalWrapperVbox = new global::Gtk.VBox ();
			this.generalWrapperVbox.Name = "generalWrapperVbox";
			this.generalWrapperVbox.Spacing = 6;
			this.generalWrapperVbox.BorderWidth = ((uint)(6));
			// Container child generalWrapperVbox.Gtk.Box+BoxChild
			this.generalFeedActionsVbox = new global::Gtk.VBox ();
			this.generalFeedActionsVbox.Name = "generalFeedActionsVbox";
			this.generalFeedActionsVbox.Spacing = 6;
			// Container child generalFeedActionsVbox.Gtk.Box+BoxChild
			this.feedActionsLbl = new global::Gtk.Label ();
			this.feedActionsLbl.Name = "feedActionsLbl";
			this.feedActionsLbl.Xalign = 0F;
			this.feedActionsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Actions</b>");
			this.feedActionsLbl.UseMarkup = true;
			this.generalFeedActionsVbox.Add (this.feedActionsLbl);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.generalFeedActionsVbox [this.feedActionsLbl]));
			w3.Position = 0;
			// Container child generalFeedActionsVbox.Gtk.Box+BoxChild
			this.feedActionBtnBox = new global::Gtk.HButtonBox ();
			this.feedActionBtnBox.Name = "feedActionBtnBox";
			this.feedActionBtnBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child feedActionBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.generalLoadDefaults = new global::Gtk.Button ();
			this.generalLoadDefaults.CanFocus = true;
			this.generalLoadDefaults.Name = "generalLoadDefaults";
			this.generalLoadDefaults.UseUnderline = true;
			this.generalLoadDefaults.Label = global::Mono.Unix.Catalog.GetString ("Load Defaults");
			this.feedActionBtnBox.Add (this.generalLoadDefaults);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.feedActionBtnBox [this.generalLoadDefaults]));
			w4.Expand = false;
			w4.Fill = false;
			this.generalFeedActionsVbox.Add (this.feedActionBtnBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.generalFeedActionsVbox [this.feedActionBtnBox]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child generalFeedActionsVbox.Gtk.Box+BoxChild
			this.generalSpacer1 = new global::Gtk.Fixed ();
			this.generalSpacer1.HeightRequest = 10;
			this.generalSpacer1.Name = "generalSpacer1";
			this.generalSpacer1.HasWindow = false;
			this.generalFeedActionsVbox.Add (this.generalSpacer1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.generalFeedActionsVbox [this.generalSpacer1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.generalWrapperVbox.Add (this.generalFeedActionsVbox);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.generalWrapperVbox [this.generalFeedActionsVbox]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child generalWrapperVbox.Gtk.Box+BoxChild
			this.generalTable = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
			this.generalTable.Name = "generalTable";
			this.generalTable.RowSpacing = ((uint)(6));
			this.generalTable.ColumnSpacing = ((uint)(6));
			// Container child generalTable.Gtk.Table+TableChild
			this.applicationSettingsLbl = new global::Gtk.Label ();
			this.applicationSettingsLbl.Name = "applicationSettingsLbl";
			this.applicationSettingsLbl.Xalign = 0F;
			this.applicationSettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Application Settings</b>");
			this.applicationSettingsLbl.UseMarkup = true;
			this.generalTable.Add (this.applicationSettingsLbl);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.generalTable [this.applicationSettingsLbl]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.customIconCb = new global::Gtk.CheckButton ();
			this.customIconCb.CanFocus = true;
			this.customIconCb.Name = "customIconCb";
			this.customIconCb.Label = "";
			this.customIconCb.DrawIndicator = true;
			this.customIconCb.FocusOnClick = false;
			this.generalTable.Add (this.customIconCb);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.generalTable [this.customIconCb]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(0));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.customIconCbLbl = new global::Gtk.Label ();
			this.customIconCbLbl.Name = "customIconCbLbl";
			this.customIconCbLbl.Xalign = 0F;
			this.customIconCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Use Custom Icon");
			this.generalTable.Add (this.customIconCbLbl);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.generalTable [this.customIconCbLbl]));
			w10.TopAttach = ((uint)(5));
			w10.BottomAttach = ((uint)(6));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.feedSettingsLbl = new global::Gtk.Label ();
			this.feedSettingsLbl.Name = "feedSettingsLbl";
			this.feedSettingsLbl.Xalign = 0F;
			this.feedSettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Feed Settings</b>");
			this.feedSettingsLbl.UseMarkup = true;
			this.generalTable.Add (this.feedSettingsLbl);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.generalTable [this.feedSettingsLbl]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.feedTitleTxt = new global::Gtk.Entry ();
			this.feedTitleTxt.CanFocus = true;
			this.feedTitleTxt.Name = "feedTitleTxt";
			this.feedTitleTxt.IsEditable = true;
			this.feedTitleTxt.InvisibleChar = '●';
			this.generalTable.Add (this.feedTitleTxt);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.generalTable [this.feedTitleTxt]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.feedUrlTxLbl = new global::Gtk.Label ();
			this.feedUrlTxLbl.Name = "feedUrlTxLbl";
			this.feedUrlTxLbl.Xalign = 0F;
			this.feedUrlTxLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Feed URL");
			this.generalTable.Add (this.feedUrlTxLbl);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.generalTable [this.feedUrlTxLbl]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.feedUrlTxt = new global::Gtk.Entry ();
			this.feedUrlTxt.CanFocus = true;
			this.feedUrlTxt.Name = "feedUrlTxt";
			this.feedUrlTxt.IsEditable = true;
			this.feedUrlTxt.InvisibleChar = '●';
			this.generalTable.Add (this.feedUrlTxt);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.generalTable [this.feedUrlTxt]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.generalSpacer2 = new global::Gtk.Fixed ();
			this.generalSpacer2.HeightRequest = 10;
			this.generalSpacer2.Name = "generalSpacer2";
			this.generalSpacer2.HasWindow = false;
			this.generalTable.Add (this.generalSpacer2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.generalTable [this.generalSpacer2]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.generalSpacer3 = new global::Gtk.Fixed ();
			this.generalSpacer3.HeightRequest = 10;
			this.generalSpacer3.Name = "generalSpacer3";
			this.generalSpacer3.HasWindow = false;
			this.generalTable.Add (this.generalSpacer3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.generalTable [this.generalSpacer3]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.iconFileSel = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.iconFileSel.Name = "iconFileSel";
			this.generalTable.Add (this.iconFileSel);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.generalTable [this.iconFileSel]));
			w17.TopAttach = ((uint)(6));
			w17.BottomAttach = ((uint)(7));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.iconFileSelLbl = new global::Gtk.Label ();
			this.iconFileSelLbl.Name = "iconFileSelLbl";
			this.iconFileSelLbl.Xalign = 0F;
			this.iconFileSelLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Icon File");
			this.generalTable.Add (this.iconFileSelLbl);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.generalTable [this.iconFileSelLbl]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.maxPostsDcLbl = new global::Gtk.Label ();
			this.maxPostsDcLbl.Name = "maxPostsDcLbl";
			this.maxPostsDcLbl.Xalign = 0F;
			this.maxPostsDcLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum Posts");
			this.generalTable.Add (this.maxPostsDcLbl);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.generalTable [this.maxPostsDcLbl]));
			w19.TopAttach = ((uint)(10));
			w19.BottomAttach = ((uint)(11));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.maxPostsDec = new global::Gtk.SpinButton (1D, 100D, 1D);
			this.maxPostsDec.CanFocus = true;
			this.maxPostsDec.Name = "maxPostsDec";
			this.maxPostsDec.Adjustment.PageIncrement = 1D;
			this.maxPostsDec.ClimbRate = 1D;
			this.maxPostsDec.Numeric = true;
			this.maxPostsDec.Value = 1D;
			this.generalTable.Add (this.maxPostsDec);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.generalTable [this.maxPostsDec]));
			w20.TopAttach = ((uint)(10));
			w20.BottomAttach = ((uint)(11));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.queryIntervalDcLbl = new global::Gtk.Label ();
			this.queryIntervalDcLbl.Name = "queryIntervalDcLbl";
			this.queryIntervalDcLbl.Xalign = 0F;
			this.queryIntervalDcLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Query Interval (sec)");
			this.generalTable.Add (this.queryIntervalDcLbl);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.generalTable [this.queryIntervalDcLbl]));
			w21.TopAttach = ((uint)(9));
			w21.BottomAttach = ((uint)(10));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.queryIntervalDec = new global::Gtk.SpinButton (10D, 10000000000D, 1D);
			this.queryIntervalDec.CanFocus = true;
			this.queryIntervalDec.Name = "queryIntervalDec";
			this.queryIntervalDec.Adjustment.PageIncrement = 1D;
			this.queryIntervalDec.ClimbRate = 1D;
			this.queryIntervalDec.Numeric = true;
			this.queryIntervalDec.Value = 10D;
			this.generalTable.Add (this.queryIntervalDec);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.generalTable [this.queryIntervalDec]));
			w22.TopAttach = ((uint)(9));
			w22.BottomAttach = ((uint)(10));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.querySettingsLbl = new global::Gtk.Label ();
			this.querySettingsLbl.Name = "querySettingsLbl";
			this.querySettingsLbl.Xalign = 0F;
			this.querySettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Query Settings</b>");
			this.querySettingsLbl.UseMarkup = true;
			this.generalTable.Add (this.querySettingsLbl);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.generalTable [this.querySettingsLbl]));
			w23.TopAttach = ((uint)(8));
			w23.BottomAttach = ((uint)(9));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child generalTable.Gtk.Table+TableChild
			this.serverNameTxLbl = new global::Gtk.Label ();
			this.serverNameTxLbl.Name = "serverNameTxLbl";
			this.serverNameTxLbl.Xalign = 0F;
			this.serverNameTxLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Feed Title");
			this.generalTable.Add (this.serverNameTxLbl);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.generalTable [this.serverNameTxLbl]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			this.generalWrapperVbox.Add (this.generalTable);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.generalWrapperVbox [this.generalTable]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			w2.Add (this.generalWrapperVbox);
			this.generalScroll.Add (w2);
			this.tabControl.Add (this.generalScroll);
			// Notebook tab
			this.generalSettingsLbl = new global::Gtk.Label ();
			this.generalSettingsLbl.Name = "generalSettingsLbl";
			this.generalSettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("General Settings");
			this.tabControl.SetTabLabel (this.generalScroll, this.generalSettingsLbl);
			this.generalSettingsLbl.ShowAll ();
			// Container child tabControl.Gtk.Notebook+NotebookChild
			this.notificationScroll = new global::Gtk.ScrolledWindow ();
			this.notificationScroll.CanFocus = true;
			this.notificationScroll.Name = "notificationScroll";
			this.notificationScroll.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.notificationScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.notificationScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child notificationScroll.Gtk.Container+ContainerChild
			global::Gtk.Viewport w29 = new global::Gtk.Viewport ();
			w29.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.notificationsWrapperVbox = new global::Gtk.VBox ();
			this.notificationsWrapperVbox.Name = "notificationsWrapperVbox";
			this.notificationsWrapperVbox.Spacing = 6;
			this.notificationsWrapperVbox.BorderWidth = ((uint)(6));
			// Container child notificationsWrapperVbox.Gtk.Box+BoxChild
			this.notificationsActionsVbox = new global::Gtk.VBox ();
			this.notificationsActionsVbox.Name = "notificationsActionsVbox";
			this.notificationsActionsVbox.Spacing = 6;
			// Container child notificationsActionsVbox.Gtk.Box+BoxChild
			this.notificationActionsLbl = new global::Gtk.Label ();
			this.notificationActionsLbl.Name = "notificationActionsLbl";
			this.notificationActionsLbl.Xalign = 0F;
			this.notificationActionsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Actions</b>");
			this.notificationActionsLbl.UseMarkup = true;
			this.notificationsActionsVbox.Add (this.notificationActionsLbl);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.notificationsActionsVbox [this.notificationActionsLbl]));
			w30.Position = 0;
			// Container child notificationsActionsVbox.Gtk.Box+BoxChild
			this.notificationActionBtnBox = new global::Gtk.HButtonBox ();
			this.notificationActionBtnBox.Name = "notificationActionBtnBox";
			this.notificationActionBtnBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child notificationActionBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.notificationLoadDefaultsBtn = new global::Gtk.Button ();
			this.notificationLoadDefaultsBtn.CanFocus = true;
			this.notificationLoadDefaultsBtn.Name = "notificationLoadDefaultsBtn";
			this.notificationLoadDefaultsBtn.UseUnderline = true;
			this.notificationLoadDefaultsBtn.Label = global::Mono.Unix.Catalog.GetString ("Load Defaults");
			this.notificationActionBtnBox.Add (this.notificationLoadDefaultsBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.notificationActionBtnBox [this.notificationLoadDefaultsBtn]));
			w31.Expand = false;
			w31.Fill = false;
			this.notificationsActionsVbox.Add (this.notificationActionBtnBox);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.notificationsActionsVbox [this.notificationActionBtnBox]));
			w32.Position = 1;
			// Container child notificationsActionsVbox.Gtk.Box+BoxChild
			this.notificationSpacer = new global::Gtk.Fixed ();
			this.notificationSpacer.HeightRequest = 10;
			this.notificationSpacer.Name = "notificationSpacer";
			this.notificationSpacer.HasWindow = false;
			this.notificationsActionsVbox.Add (this.notificationSpacer);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.notificationsActionsVbox [this.notificationSpacer]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.notificationsWrapperVbox.Add (this.notificationsActionsVbox);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.notificationsWrapperVbox [this.notificationsActionsVbox]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child notificationsWrapperVbox.Gtk.Box+BoxChild
			this.notificationTable = new global::Gtk.Table (((uint)(15)), ((uint)(2)), false);
			this.notificationTable.Name = "notificationTable";
			this.notificationTable.RowSpacing = ((uint)(6));
			this.notificationTable.ColumnSpacing = ((uint)(6));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotificationsLbl = new global::Gtk.Label ();
			this.audioNotificationsLbl.Name = "audioNotificationsLbl";
			this.audioNotificationsLbl.Xalign = 0F;
			this.audioNotificationsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Audio Notifications</b>");
			this.audioNotificationsLbl.UseMarkup = true;
			this.notificationTable.Add (this.audioNotificationsLbl);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotificationsLbl]));
			w35.TopAttach = ((uint)(11));
			w35.BottomAttach = ((uint)(12));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyCustomAudioCb = new global::Gtk.CheckButton ();
			this.audioNotifyCustomAudioCb.CanFocus = true;
			this.audioNotifyCustomAudioCb.Name = "audioNotifyCustomAudioCb";
			this.audioNotifyCustomAudioCb.Label = "";
			this.audioNotifyCustomAudioCb.DrawIndicator = true;
			this.audioNotifyCustomAudioCb.FocusOnClick = false;
			this.notificationTable.Add (this.audioNotifyCustomAudioCb);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyCustomAudioCb]));
			w36.TopAttach = ((uint)(13));
			w36.BottomAttach = ((uint)(14));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(0));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyCustomAudioCbLbl = new global::Gtk.Label ();
			this.audioNotifyCustomAudioCbLbl.Name = "audioNotifyCustomAudioCbLbl";
			this.audioNotifyCustomAudioCbLbl.Xalign = 0F;
			this.audioNotifyCustomAudioCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Use Custom Audio");
			this.notificationTable.Add (this.audioNotifyCustomAudioCbLbl);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyCustomAudioCbLbl]));
			w37.TopAttach = ((uint)(13));
			w37.BottomAttach = ((uint)(14));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyEnabledCb = new global::Gtk.CheckButton ();
			this.audioNotifyEnabledCb.CanFocus = true;
			this.audioNotifyEnabledCb.Name = "audioNotifyEnabledCb";
			this.audioNotifyEnabledCb.Label = "";
			this.audioNotifyEnabledCb.DrawIndicator = true;
			this.audioNotifyEnabledCb.FocusOnClick = false;
			this.notificationTable.Add (this.audioNotifyEnabledCb);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyEnabledCb]));
			w38.TopAttach = ((uint)(12));
			w38.BottomAttach = ((uint)(13));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(0));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyEnabledCbLbl = new global::Gtk.Label ();
			this.audioNotifyEnabledCbLbl.Name = "audioNotifyEnabledCbLbl";
			this.audioNotifyEnabledCbLbl.Xalign = 0F;
			this.audioNotifyEnabledCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Enabled");
			this.notificationTable.Add (this.audioNotifyEnabledCbLbl);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyEnabledCbLbl]));
			w39.TopAttach = ((uint)(12));
			w39.BottomAttach = ((uint)(13));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyFileSel = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.audioNotifyFileSel.Name = "audioNotifyFileSel";
			this.notificationTable.Add (this.audioNotifyFileSel);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyFileSel]));
			w40.TopAttach = ((uint)(14));
			w40.BottomAttach = ((uint)(15));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.audioNotifyFileSelLbl = new global::Gtk.Label ();
			this.audioNotifyFileSelLbl.Name = "audioNotifyFileSelLbl";
			this.audioNotifyFileSelLbl.Xalign = 0F;
			this.audioNotifyFileSelLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Custom Wave File");
			this.notificationTable.Add (this.audioNotifyFileSelLbl);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.audioNotifyFileSelLbl]));
			w41.TopAttach = ((uint)(14));
			w41.BottomAttach = ((uint)(15));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.notificationSpacer1 = new global::Gtk.Fixed ();
			this.notificationSpacer1.HeightRequest = 10;
			this.notificationSpacer1.Name = "notificationSpacer1";
			this.notificationSpacer1.HasWindow = false;
			this.notificationTable.Add (this.notificationSpacer1);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.notificationSpacer1]));
			w42.TopAttach = ((uint)(6));
			w42.BottomAttach = ((uint)(7));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.notificationSpacer2 = new global::Gtk.Fixed ();
			this.notificationSpacer2.HeightRequest = 10;
			this.notificationSpacer2.Name = "notificationSpacer2";
			this.notificationSpacer2.HasWindow = false;
			this.notificationTable.Add (this.notificationSpacer2);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.notificationSpacer2]));
			w43.TopAttach = ((uint)(10));
			w43.BottomAttach = ((uint)(11));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.taskbarIconCounterPositionLbl = new global::Gtk.Label ();
			this.taskbarIconCounterPositionLbl.Name = "taskbarIconCounterPositionLbl";
			this.taskbarIconCounterPositionLbl.Xalign = 0F;
			this.taskbarIconCounterPositionLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Unread counter position");
			this.notificationTable.Add (this.taskbarIconCounterPositionLbl);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.taskbarIconCounterPositionLbl]));
			w44.TopAttach = ((uint)(9));
			w44.BottomAttach = ((uint)(10));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.taskbarIconEnableUnreadLbl = new global::Gtk.Label ();
			this.taskbarIconEnableUnreadLbl.Name = "taskbarIconEnableUnreadLbl";
			this.taskbarIconEnableUnreadLbl.Xalign = 0F;
			this.taskbarIconEnableUnreadLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Enable unread counter");
			this.notificationTable.Add (this.taskbarIconEnableUnreadLbl);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.taskbarIconEnableUnreadLbl]));
			w45.TopAttach = ((uint)(8));
			w45.BottomAttach = ((uint)(9));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.taskbarIconLbl = new global::Gtk.Label ();
			this.taskbarIconLbl.Name = "taskbarIconLbl";
			this.taskbarIconLbl.Xalign = 0F;
			this.taskbarIconLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Taskbar icon</b>");
			this.taskbarIconLbl.UseMarkup = true;
			this.notificationTable.Add (this.taskbarIconLbl);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.taskbarIconLbl]));
			w46.TopAttach = ((uint)(7));
			w46.BottomAttach = ((uint)(8));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.taskbarIconUnreadEnabledCb = new global::Gtk.CheckButton ();
			this.taskbarIconUnreadEnabledCb.CanFocus = true;
			this.taskbarIconUnreadEnabledCb.Name = "taskbarIconUnreadEnabledCb";
			this.taskbarIconUnreadEnabledCb.Label = "";
			this.taskbarIconUnreadEnabledCb.DrawIndicator = true;
			this.taskbarIconUnreadEnabledCb.FocusOnClick = false;
			this.notificationTable.Add (this.taskbarIconUnreadEnabledCb);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.taskbarIconUnreadEnabledCb]));
			w47.TopAttach = ((uint)(8));
			w47.BottomAttach = ((uint)(9));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(0));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.taskbarIconUnreadPositionCbx = global::Gtk.ComboBox.NewText ();
			this.taskbarIconUnreadPositionCbx.AppendText (global::Mono.Unix.Catalog.GetString ("Top Left"));
			this.taskbarIconUnreadPositionCbx.AppendText (global::Mono.Unix.Catalog.GetString ("Top Right"));
			this.taskbarIconUnreadPositionCbx.AppendText (global::Mono.Unix.Catalog.GetString ("Bottom Left"));
			this.taskbarIconUnreadPositionCbx.AppendText (global::Mono.Unix.Catalog.GetString ("Bottom Right"));
			this.taskbarIconUnreadPositionCbx.Name = "taskbarIconUnreadPositionCbx";
			this.taskbarIconUnreadPositionCbx.Active = 0;
			this.notificationTable.Add (this.taskbarIconUnreadPositionCbx);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.taskbarIconUnreadPositionCbx]));
			w48.TopAttach = ((uint)(9));
			w48.BottomAttach = ((uint)(10));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotificationsLbl = new global::Gtk.Label ();
			this.visualNotificationsLbl.Name = "visualNotificationsLbl";
			this.visualNotificationsLbl.Xalign = 0F;
			this.visualNotificationsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Visual Notifications</b>");
			this.visualNotificationsLbl.UseMarkup = true;
			this.notificationTable.Add (this.visualNotificationsLbl);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotificationsLbl]));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyAnimationCb = new global::Gtk.CheckButton ();
			this.visualNotifyAnimationCb.CanFocus = true;
			this.visualNotifyAnimationCb.Name = "visualNotifyAnimationCb";
			this.visualNotifyAnimationCb.Label = "";
			this.visualNotifyAnimationCb.DrawIndicator = true;
			this.visualNotifyAnimationCb.UseUnderline = true;
			this.visualNotifyAnimationCb.FocusOnClick = false;
			this.notificationTable.Add (this.visualNotifyAnimationCb);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyAnimationCb]));
			w50.TopAttach = ((uint)(3));
			w50.BottomAttach = ((uint)(4));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(0));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyAnimationCbLbl = new global::Gtk.Label ();
			this.visualNotifyAnimationCbLbl.Name = "visualNotifyAnimationCbLbl";
			this.visualNotifyAnimationCbLbl.Xalign = 0F;
			this.visualNotifyAnimationCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Do Animation");
			this.notificationTable.Add (this.visualNotifyAnimationCbLbl);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyAnimationCbLbl]));
			w51.TopAttach = ((uint)(3));
			w51.BottomAttach = ((uint)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyAnimationIntervalDec = new global::Gtk.SpinButton (1D, 1000D, 1D);
			this.visualNotifyAnimationIntervalDec.CanFocus = true;
			this.visualNotifyAnimationIntervalDec.Name = "visualNotifyAnimationIntervalDec";
			this.visualNotifyAnimationIntervalDec.Adjustment.PageIncrement = 10D;
			this.visualNotifyAnimationIntervalDec.ClimbRate = 1D;
			this.visualNotifyAnimationIntervalDec.Numeric = true;
			this.visualNotifyAnimationIntervalDec.Value = 10D;
			this.notificationTable.Add (this.visualNotifyAnimationIntervalDec);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyAnimationIntervalDec]));
			w52.TopAttach = ((uint)(4));
			w52.BottomAttach = ((uint)(5));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyAnimationIntervalDecLbl = new global::Gtk.Label ();
			this.visualNotifyAnimationIntervalDecLbl.Name = "visualNotifyAnimationIntervalDecLbl";
			this.visualNotifyAnimationIntervalDecLbl.Xalign = 0F;
			this.visualNotifyAnimationIntervalDecLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Animation Interval (msec)");
			this.notificationTable.Add (this.visualNotifyAnimationIntervalDecLbl);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyAnimationIntervalDecLbl]));
			w53.TopAttach = ((uint)(4));
			w53.BottomAttach = ((uint)(5));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyEnabledCb = new global::Gtk.CheckButton ();
			this.visualNotifyEnabledCb.CanFocus = true;
			this.visualNotifyEnabledCb.Name = "visualNotifyEnabledCb";
			this.visualNotifyEnabledCb.Label = "";
			this.visualNotifyEnabledCb.DrawIndicator = true;
			this.visualNotifyEnabledCb.FocusOnClick = false;
			this.notificationTable.Add (this.visualNotifyEnabledCb);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyEnabledCb]));
			w54.TopAttach = ((uint)(1));
			w54.BottomAttach = ((uint)(2));
			w54.LeftAttach = ((uint)(1));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(0));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyEnabledCbLbl = new global::Gtk.Label ();
			this.visualNotifyEnabledCbLbl.Name = "visualNotifyEnabledCbLbl";
			this.visualNotifyEnabledCbLbl.Xalign = 0F;
			this.visualNotifyEnabledCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Enabled");
			this.notificationTable.Add (this.visualNotifyEnabledCbLbl);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyEnabledCbLbl]));
			w55.TopAttach = ((uint)(1));
			w55.BottomAttach = ((uint)(2));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyTimeoutDec = new global::Gtk.SpinButton (1D, 1000D, 1D);
			this.visualNotifyTimeoutDec.CanFocus = true;
			this.visualNotifyTimeoutDec.Name = "visualNotifyTimeoutDec";
			this.visualNotifyTimeoutDec.Adjustment.PageIncrement = 10D;
			this.visualNotifyTimeoutDec.ClimbRate = 1D;
			this.visualNotifyTimeoutDec.Numeric = true;
			this.visualNotifyTimeoutDec.Value = 1D;
			this.notificationTable.Add (this.visualNotifyTimeoutDec);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyTimeoutDec]));
			w56.TopAttach = ((uint)(5));
			w56.BottomAttach = ((uint)(6));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyTimeoutDecLbl = new global::Gtk.Label ();
			this.visualNotifyTimeoutDecLbl.Name = "visualNotifyTimeoutDecLbl";
			this.visualNotifyTimeoutDecLbl.Xalign = 0F;
			this.visualNotifyTimeoutDecLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Timeout (sec)");
			this.notificationTable.Add (this.visualNotifyTimeoutDecLbl);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyTimeoutDecLbl]));
			w57.TopAttach = ((uint)(5));
			w57.BottomAttach = ((uint)(6));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyVerticalAlignmentSlide = new global::Gtk.HScale (null);
			this.visualNotifyVerticalAlignmentSlide.CanFocus = true;
			this.visualNotifyVerticalAlignmentSlide.Name = "visualNotifyVerticalAlignmentSlide";
			this.visualNotifyVerticalAlignmentSlide.Adjustment.Upper = 1D;
			this.visualNotifyVerticalAlignmentSlide.Adjustment.PageIncrement = 0.1D;
			this.visualNotifyVerticalAlignmentSlide.Adjustment.StepIncrement = 0.01D;
			this.visualNotifyVerticalAlignmentSlide.DrawValue = true;
			this.visualNotifyVerticalAlignmentSlide.Digits = 2;
			this.visualNotifyVerticalAlignmentSlide.ValuePos = ((global::Gtk.PositionType)(2));
			this.notificationTable.Add (this.visualNotifyVerticalAlignmentSlide);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyVerticalAlignmentSlide]));
			w58.TopAttach = ((uint)(2));
			w58.BottomAttach = ((uint)(3));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child notificationTable.Gtk.Table+TableChild
			this.visualNotifyVerticalAlignmentSlideLbl = new global::Gtk.Label ();
			this.visualNotifyVerticalAlignmentSlideLbl.Name = "visualNotifyVerticalAlignmentSlideLbl";
			this.visualNotifyVerticalAlignmentSlideLbl.Xalign = 0F;
			this.visualNotifyVerticalAlignmentSlideLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Vertical Alignment");
			this.notificationTable.Add (this.visualNotifyVerticalAlignmentSlideLbl);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.notificationTable [this.visualNotifyVerticalAlignmentSlideLbl]));
			w59.TopAttach = ((uint)(2));
			w59.BottomAttach = ((uint)(3));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notificationsWrapperVbox.Add (this.notificationTable);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.notificationsWrapperVbox [this.notificationTable]));
			w60.Position = 1;
			w60.Expand = false;
			w60.Fill = false;
			w29.Add (this.notificationsWrapperVbox);
			this.notificationScroll.Add (w29);
			this.tabControl.Add (this.notificationScroll);
			global::Gtk.Notebook.NotebookChild w63 = ((global::Gtk.Notebook.NotebookChild)(this.tabControl [this.notificationScroll]));
			w63.Position = 1;
			// Notebook tab
			this.notificationSettingsLbl = new global::Gtk.Label ();
			this.notificationSettingsLbl.Name = "notificationSettingsLbl";
			this.notificationSettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Notification Settings");
			this.tabControl.SetTabLabel (this.notificationScroll, this.notificationSettingsLbl);
			this.notificationSettingsLbl.ShowAll ();
			// Container child tabControl.Gtk.Notebook+NotebookChild
			this.contentScroll = new global::Gtk.ScrolledWindow ();
			this.contentScroll.CanFocus = true;
			this.contentScroll.Name = "contentScroll";
			this.contentScroll.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.contentScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.contentScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child contentScroll.Gtk.Container+ContainerChild
			global::Gtk.Viewport w64 = new global::Gtk.Viewport ();
			w64.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport3.Gtk.Container+ContainerChild
			this.contentWrapperVbox = new global::Gtk.VBox ();
			this.contentWrapperVbox.Name = "contentWrapperVbox";
			this.contentWrapperVbox.Spacing = 6;
			this.contentWrapperVbox.BorderWidth = ((uint)(6));
			// Container child contentWrapperVbox.Gtk.Box+BoxChild
			this.contentActionsVbox = new global::Gtk.VBox ();
			this.contentActionsVbox.Name = "contentActionsVbox";
			this.contentActionsVbox.Spacing = 6;
			// Container child contentActionsVbox.Gtk.Box+BoxChild
			this.contentActionsLbl = new global::Gtk.Label ();
			this.contentActionsLbl.Name = "contentActionsLbl";
			this.contentActionsLbl.Xalign = 0F;
			this.contentActionsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Actions</b>");
			this.contentActionsLbl.UseMarkup = true;
			this.contentActionsVbox.Add (this.contentActionsLbl);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.contentActionsVbox [this.contentActionsLbl]));
			w65.Position = 0;
			// Container child contentActionsVbox.Gtk.Box+BoxChild
			this.contentActionBtnBox = new global::Gtk.HButtonBox ();
			this.contentActionBtnBox.Name = "contentActionBtnBox";
			this.contentActionBtnBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child contentActionBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.contentLoadDefaultsBtn = new global::Gtk.Button ();
			this.contentLoadDefaultsBtn.CanFocus = true;
			this.contentLoadDefaultsBtn.Name = "contentLoadDefaultsBtn";
			this.contentLoadDefaultsBtn.UseUnderline = true;
			this.contentLoadDefaultsBtn.Label = global::Mono.Unix.Catalog.GetString ("Load Defaults");
			this.contentActionBtnBox.Add (this.contentLoadDefaultsBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w66 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.contentActionBtnBox [this.contentLoadDefaultsBtn]));
			w66.Expand = false;
			w66.Fill = false;
			this.contentActionsVbox.Add (this.contentActionBtnBox);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.contentActionsVbox [this.contentActionBtnBox]));
			w67.Position = 1;
			// Container child contentActionsVbox.Gtk.Box+BoxChild
			this.contentSpacer1 = new global::Gtk.Fixed ();
			this.contentSpacer1.HeightRequest = 10;
			this.contentSpacer1.Name = "contentSpacer1";
			this.contentSpacer1.HasWindow = false;
			this.contentActionsVbox.Add (this.contentSpacer1);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.contentActionsVbox [this.contentSpacer1]));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			this.contentWrapperVbox.Add (this.contentActionsVbox);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.contentWrapperVbox [this.contentActionsVbox]));
			w69.Position = 0;
			w69.Expand = false;
			w69.Fill = false;
			// Container child contentWrapperVbox.Gtk.Box+BoxChild
			this.contentTable = new global::Gtk.Table (((uint)(14)), ((uint)(2)), false);
			this.contentTable.Name = "contentTable";
			this.contentTable.RowSpacing = ((uint)(6));
			this.contentTable.ColumnSpacing = ((uint)(6));
			// Container child contentTable.Gtk.Table+TableChild
			this.contentSpacer2 = new global::Gtk.Fixed ();
			this.contentSpacer2.HeightRequest = 10;
			this.contentSpacer2.Name = "contentSpacer2";
			this.contentSpacer2.HasWindow = false;
			this.contentTable.Add (this.contentSpacer2);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.contentTable [this.contentSpacer2]));
			w70.TopAttach = ((uint)(2));
			w70.BottomAttach = ((uint)(3));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.contentSpacer3 = new global::Gtk.Fixed ();
			this.contentSpacer3.HeightRequest = 10;
			this.contentSpacer3.Name = "contentSpacer3";
			this.contentSpacer3.HasWindow = false;
			this.contentTable.Add (this.contentSpacer3);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.contentTable [this.contentSpacer3]));
			w71.TopAttach = ((uint)(5));
			w71.BottomAttach = ((uint)(6));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.contentSpacer4 = new global::Gtk.Fixed ();
			this.contentSpacer4.HeightRequest = 10;
			this.contentSpacer4.Name = "contentSpacer4";
			this.contentSpacer4.HasWindow = false;
			this.contentTable.Add (this.contentSpacer4);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.contentTable [this.contentSpacer4]));
			w72.TopAttach = ((uint)(8));
			w72.BottomAttach = ((uint)(9));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.contentSpacer5 = new global::Gtk.Fixed ();
			this.contentSpacer5.HeightRequest = 10;
			this.contentSpacer5.Name = "contentSpacer5";
			this.contentSpacer5.HasWindow = false;
			this.contentTable.Add (this.contentSpacer5);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.contentTable [this.contentSpacer5]));
			w73.TopAttach = ((uint)(11));
			w73.BottomAttach = ((uint)(12));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.displaySettingsLbl = new global::Gtk.Label ();
			this.displaySettingsLbl.Name = "displaySettingsLbl";
			this.displaySettingsLbl.Xalign = 0F;
			this.displaySettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Display Settings</b>");
			this.displaySettingsLbl.UseMarkup = true;
			this.contentTable.Add (this.displaySettingsLbl);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.contentTable [this.displaySettingsLbl]));
			w74.RightAttach = ((uint)(2));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.hideIgnoredPostsCb = new global::Gtk.CheckButton ();
			this.hideIgnoredPostsCb.CanFocus = true;
			this.hideIgnoredPostsCb.Name = "hideIgnoredPostsCb";
			this.hideIgnoredPostsCb.Label = "";
			this.hideIgnoredPostsCb.DrawIndicator = true;
			this.hideIgnoredPostsCb.UseUnderline = true;
			this.hideIgnoredPostsCb.FocusOnClick = false;
			this.contentTable.Add (this.hideIgnoredPostsCb);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.contentTable [this.hideIgnoredPostsCb]));
			w75.TopAttach = ((uint)(1));
			w75.BottomAttach = ((uint)(2));
			w75.LeftAttach = ((uint)(1));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(0));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.hideIgnoredPostsCbLbl = new global::Gtk.Label ();
			this.hideIgnoredPostsCbLbl.Name = "hideIgnoredPostsCbLbl";
			this.hideIgnoredPostsCbLbl.Xalign = 0F;
			this.hideIgnoredPostsCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Hide Ignored Posts");
			this.contentTable.Add (this.hideIgnoredPostsCbLbl);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.contentTable [this.hideIgnoredPostsCbLbl]));
			w76.TopAttach = ((uint)(1));
			w76.BottomAttach = ((uint)(2));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignoredPostsLbl = new global::Gtk.Label ();
			this.ignoredPostsLbl.Name = "ignoredPostsLbl";
			this.ignoredPostsLbl.Xalign = 0F;
			this.ignoredPostsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ignored Posts</b>");
			this.ignoredPostsLbl.UseMarkup = true;
			this.contentTable.Add (this.ignoredPostsLbl);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignoredPostsLbl]));
			w77.TopAttach = ((uint)(9));
			w77.BottomAttach = ((uint)(10));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignoredTopicsLbl = new global::Gtk.Label ();
			this.ignoredTopicsLbl.Name = "ignoredTopicsLbl";
			this.ignoredTopicsLbl.Xalign = 0F;
			this.ignoredTopicsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ignored Topics</b>");
			this.ignoredTopicsLbl.UseMarkup = true;
			this.contentTable.Add (this.ignoredTopicsLbl);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignoredTopicsLbl]));
			w78.TopAttach = ((uint)(3));
			w78.BottomAttach = ((uint)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignoredUsersLbl = new global::Gtk.Label ();
			this.ignoredUsersLbl.Name = "ignoredUsersLbl";
			this.ignoredUsersLbl.Xalign = 0F;
			this.ignoredUsersLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><s>Ignored Users</s> (deprecated)</b>");
			this.ignoredUsersLbl.UseMarkup = true;
			this.contentTable.Add (this.ignoredUsersLbl);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignoredUsersLbl]));
			w79.TopAttach = ((uint)(6));
			w79.BottomAttach = ((uint)(7));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignTopicsBtnBox = new global::Gtk.HButtonBox ();
			this.ignTopicsBtnBox.Name = "ignTopicsBtnBox";
			this.ignTopicsBtnBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child ignTopicsBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.ignTopicAddBtn = new global::Gtk.Button ();
			this.ignTopicAddBtn.CanFocus = true;
			this.ignTopicAddBtn.Name = "ignTopicAddBtn";
			this.ignTopicAddBtn.UseUnderline = true;
			this.ignTopicAddBtn.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.ignTopicsBtnBox.Add (this.ignTopicAddBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w80 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ignTopicsBtnBox [this.ignTopicAddBtn]));
			w80.Expand = false;
			w80.Fill = false;
			// Container child ignTopicsBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.ignTopicsRemoveBtn = new global::Gtk.Button ();
			this.ignTopicsRemoveBtn.CanFocus = true;
			this.ignTopicsRemoveBtn.Name = "ignTopicsRemoveBtn";
			this.ignTopicsRemoveBtn.UseUnderline = true;
			this.ignTopicsRemoveBtn.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.ignTopicsBtnBox.Add (this.ignTopicsRemoveBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w81 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ignTopicsBtnBox [this.ignTopicsRemoveBtn]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			this.contentTable.Add (this.ignTopicsBtnBox);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignTopicsBtnBox]));
			w82.TopAttach = ((uint)(4));
			w82.BottomAttach = ((uint)(5));
			w82.LeftAttach = ((uint)(1));
			w82.RightAttach = ((uint)(2));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignTopicsComboEntry = global::Gtk.ComboBoxEntry.NewText ();
			this.ignTopicsComboEntry.Name = "ignTopicsComboEntry";
			this.contentTable.Add (this.ignTopicsComboEntry);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignTopicsComboEntry]));
			w83.TopAttach = ((uint)(4));
			w83.BottomAttach = ((uint)(5));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignUsersBtnBox = new global::Gtk.HButtonBox ();
			this.ignUsersBtnBox.Name = "ignUsersBtnBox";
			this.ignUsersBtnBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child ignUsersBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.ignUsersAddBtn = new global::Gtk.Button ();
			this.ignUsersAddBtn.Sensitive = false;
			this.ignUsersAddBtn.CanFocus = true;
			this.ignUsersAddBtn.Name = "ignUsersAddBtn";
			this.ignUsersAddBtn.UseUnderline = true;
			this.ignUsersAddBtn.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.ignUsersBtnBox.Add (this.ignUsersAddBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w84 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ignUsersBtnBox [this.ignUsersAddBtn]));
			w84.Expand = false;
			w84.Fill = false;
			// Container child ignUsersBtnBox.Gtk.ButtonBox+ButtonBoxChild
			this.ignUsersRemoveBtn = new global::Gtk.Button ();
			this.ignUsersRemoveBtn.Sensitive = false;
			this.ignUsersRemoveBtn.CanFocus = true;
			this.ignUsersRemoveBtn.Name = "ignUsersRemoveBtn";
			this.ignUsersRemoveBtn.UseUnderline = true;
			this.ignUsersRemoveBtn.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.ignUsersBtnBox.Add (this.ignUsersRemoveBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w85 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.ignUsersBtnBox [this.ignUsersRemoveBtn]));
			w85.Position = 1;
			w85.Expand = false;
			w85.Fill = false;
			this.contentTable.Add (this.ignUsersBtnBox);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignUsersBtnBox]));
			w86.TopAttach = ((uint)(7));
			w86.BottomAttach = ((uint)(8));
			w86.LeftAttach = ((uint)(1));
			w86.RightAttach = ((uint)(2));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.ignUsersComboEntry = global::Gtk.ComboBoxEntry.NewText ();
			this.ignUsersComboEntry.Sensitive = false;
			this.ignUsersComboEntry.Name = "ignUsersComboEntry";
			this.contentTable.Add (this.ignUsersComboEntry);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.contentTable [this.ignUsersComboEntry]));
			w87.TopAttach = ((uint)(7));
			w87.BottomAttach = ((uint)(8));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.minWordcountDecLbl = new global::Gtk.Label ();
			this.minWordcountDecLbl.Name = "minWordcountDecLbl";
			this.minWordcountDecLbl.Xalign = 0F;
			this.minWordcountDecLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Minimum Words");
			this.contentTable.Add (this.minWordcountDecLbl);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.contentTable [this.minWordcountDecLbl]));
			w88.TopAttach = ((uint)(10));
			w88.BottomAttach = ((uint)(11));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.minWordsDec = new global::Gtk.SpinButton (0D, 350D, 1D);
			this.minWordsDec.CanFocus = true;
			this.minWordsDec.Name = "minWordsDec";
			this.minWordsDec.Adjustment.PageIncrement = 10D;
			this.minWordsDec.ClimbRate = 1D;
			this.minWordsDec.Numeric = true;
			this.contentTable.Add (this.minWordsDec);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.contentTable [this.minWordsDec]));
			w89.TopAttach = ((uint)(10));
			w89.BottomAttach = ((uint)(11));
			w89.LeftAttach = ((uint)(1));
			w89.RightAttach = ((uint)(2));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.syntaxInfoLbl = new global::Gtk.Label ();
			this.syntaxInfoLbl.Name = "syntaxInfoLbl";
			this.syntaxInfoLbl.Xalign = 0F;
			this.syntaxInfoLbl.LabelProp = global::Mono.Unix.Catalog.GetString (@"<i>You know the ID is 25?</i>
Then enter: <span bgcolor='gray'>#25</span>
<span bgcolor='yellow'>Note:</span> You can also use <span bgcolor='gray'>(25)</span> or <span bgcolor='gray'>25:</span>.

<i>You know the name contains: <span bgcolor='white'>Yourself</span>?</i>
Then enter <span bgcolor='gray'>@[.*Yourself:.*]</span>
<span bgcolor='yellow'>Note:</span> You can use any valid regex in this @[] syntax. The regex is case sensitive!

<i>You know the name is: <span bgcolor='white'>Introduce Yourself</span>?</i>
Then enter <span bgcolor='gray'>Introduce Yourself</span>
<span bgcolor='yellow'>Note:</span> In this syntax, you might only use alphanumeric characters, numbers, underscores and spaces! Also all preceeding and following spaces are stripped.

<i>You know the name is: <span bgcolor='white'>Introduce Yourself :)</span>?</i>
Then enter <span bgcolor='gray'>""Introduce Yourself :)""</span>

<i> You know the ID is 1 and want to provide a name for easier managing?</i>
Then enter <span bgcolor='gray'>1: Forum Admin</span>
<span bgcolor='yellow'>Note:</span> You can also use <span bgcolor='gray'>(1) Introduce Yourself</span>, <span bgcolor='gray'>1 / Introduce Yourself</span> and <span bgcolor='gray'>#1 Introduce Yourself</span>.

You can mix these however you want.");
			this.syntaxInfoLbl.UseMarkup = true;
			this.syntaxInfoLbl.Wrap = true;
			this.contentTable.Add (this.syntaxInfoLbl);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.contentTable [this.syntaxInfoLbl]));
			w90.TopAttach = ((uint)(13));
			w90.BottomAttach = ((uint)(14));
			w90.RightAttach = ((uint)(2));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.syntaxInfoLblLbl = new global::Gtk.Label ();
			this.syntaxInfoLblLbl.Name = "syntaxInfoLblLbl";
			this.syntaxInfoLblLbl.Xalign = 0F;
			this.syntaxInfoLblLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Syntax Info</b>");
			this.syntaxInfoLblLbl.UseMarkup = true;
			this.contentTable.Add (this.syntaxInfoLblLbl);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.contentTable [this.syntaxInfoLblLbl]));
			w91.TopAttach = ((uint)(12));
			w91.BottomAttach = ((uint)(13));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			this.contentWrapperVbox.Add (this.contentTable);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.contentWrapperVbox [this.contentTable]));
			w92.Position = 1;
			w92.Expand = false;
			w92.Fill = false;
			w64.Add (this.contentWrapperVbox);
			this.contentScroll.Add (w64);
			this.tabControl.Add (this.contentScroll);
			global::Gtk.Notebook.NotebookChild w95 = ((global::Gtk.Notebook.NotebookChild)(this.tabControl [this.contentScroll]));
			w95.Position = 2;
			// Notebook tab
			this.contentScrollLbl = new global::Gtk.Label ();
			this.contentScrollLbl.Name = "contentScrollLbl";
			this.contentScrollLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Content Settings");
			this.tabControl.SetTabLabel (this.contentScroll, this.contentScrollLbl);
			this.contentScrollLbl.ShowAll ();
			// Container child tabControl.Gtk.Notebook+NotebookChild
			this.styleScroll = new global::Gtk.ScrolledWindow ();
			this.styleScroll.CanFocus = true;
			this.styleScroll.Name = "styleScroll";
			this.styleScroll.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.styleScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.styleScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child styleScroll.Gtk.Container+ContainerChild
			global::Gtk.Viewport w96 = new global::Gtk.Viewport ();
			w96.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.styleWrapperVbox = new global::Gtk.VBox ();
			this.styleWrapperVbox.Name = "styleWrapperVbox";
			this.styleWrapperVbox.Spacing = 6;
			this.styleWrapperVbox.BorderWidth = ((uint)(6));
			// Container child styleWrapperVbox.Gtk.Box+BoxChild
			this.styleActionsVbox = new global::Gtk.VBox ();
			this.styleActionsVbox.Name = "styleActionsVbox";
			this.styleActionsVbox.Spacing = 6;
			// Container child styleActionsVbox.Gtk.Box+BoxChild
			this.styleActionsLbl = new global::Gtk.Label ();
			this.styleActionsLbl.Name = "styleActionsLbl";
			this.styleActionsLbl.Xalign = 0F;
			this.styleActionsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Actions</b>");
			this.styleActionsLbl.UseMarkup = true;
			this.styleActionsVbox.Add (this.styleActionsLbl);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.styleActionsVbox [this.styleActionsLbl]));
			w97.Position = 0;
			// Container child styleActionsVbox.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.stylesLoadDefaultsBtn = new global::Gtk.Button ();
			this.stylesLoadDefaultsBtn.CanFocus = true;
			this.stylesLoadDefaultsBtn.Name = "stylesLoadDefaultsBtn";
			this.stylesLoadDefaultsBtn.UseUnderline = true;
			this.stylesLoadDefaultsBtn.Label = global::Mono.Unix.Catalog.GetString ("Load Defaults");
			this.hbuttonbox2.Add (this.stylesLoadDefaultsBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w98 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.stylesLoadDefaultsBtn]));
			w98.Expand = false;
			w98.Fill = false;
			this.styleActionsVbox.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.styleActionsVbox [this.hbuttonbox2]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			// Container child styleActionsVbox.Gtk.Box+BoxChild
			this.styleSpacer1 = new global::Gtk.Fixed ();
			this.styleSpacer1.HeightRequest = 10;
			this.styleSpacer1.Name = "styleSpacer1";
			this.styleSpacer1.HasWindow = false;
			this.styleActionsVbox.Add (this.styleSpacer1);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.styleActionsVbox [this.styleSpacer1]));
			w100.Position = 2;
			w100.Expand = false;
			w100.Fill = false;
			this.styleWrapperVbox.Add (this.styleActionsVbox);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.styleWrapperVbox [this.styleActionsVbox]));
			w101.Position = 0;
			w101.Expand = false;
			w101.Fill = false;
			// Container child styleWrapperVbox.Gtk.Box+BoxChild
			this.styleTable = new global::Gtk.Table (((uint)(16)), ((uint)(2)), false);
			this.styleTable.Name = "styleTable";
			this.styleTable.RowSpacing = ((uint)(6));
			this.styleTable.ColumnSpacing = ((uint)(6));
			// Container child styleTable.Gtk.Table+TableChild
			this.authorFgClLbl = new global::Gtk.Label ();
			this.authorFgClLbl.Name = "authorFgClLbl";
			this.authorFgClLbl.Xalign = 0F;
			this.authorFgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Author Forecolor");
			this.styleTable.Add (this.authorFgClLbl);
			global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.styleTable [this.authorFgClLbl]));
			w102.TopAttach = ((uint)(6));
			w102.BottomAttach = ((uint)(7));
			w102.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.authorFgColorBtn = new global::Gtk.ColorButton ();
			this.authorFgColorBtn.CanFocus = true;
			this.authorFgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.authorFgColorBtn.Name = "authorFgColorBtn";
			this.styleTable.Add (this.authorFgColorBtn);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.styleTable [this.authorFgColorBtn]));
			w103.TopAttach = ((uint)(6));
			w103.BottomAttach = ((uint)(7));
			w103.LeftAttach = ((uint)(1));
			w103.RightAttach = ((uint)(2));
			w103.XOptions = ((global::Gtk.AttachOptions)(1));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyAntiAliasCb = new global::Gtk.CheckButton ();
			this.bodyAntiAliasCb.CanFocus = true;
			this.bodyAntiAliasCb.Name = "bodyAntiAliasCb";
			this.bodyAntiAliasCb.Label = "";
			this.bodyAntiAliasCb.DrawIndicator = true;
			this.bodyAntiAliasCb.FocusOnClick = false;
			this.styleTable.Add (this.bodyAntiAliasCb);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyAntiAliasCb]));
			w104.TopAttach = ((uint)(15));
			w104.BottomAttach = ((uint)(16));
			w104.LeftAttach = ((uint)(1));
			w104.RightAttach = ((uint)(2));
			w104.XOptions = ((global::Gtk.AttachOptions)(0));
			w104.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyAntiAliasCbLbl = new global::Gtk.Label ();
			this.bodyAntiAliasCbLbl.Name = "bodyAntiAliasCbLbl";
			this.bodyAntiAliasCbLbl.Xalign = 0F;
			this.bodyAntiAliasCbLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Body Use Anti Alias");
			this.styleTable.Add (this.bodyAntiAliasCbLbl);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyAntiAliasCbLbl]));
			w105.TopAttach = ((uint)(15));
			w105.BottomAttach = ((uint)(16));
			w105.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyBgClLbl = new global::Gtk.Label ();
			this.bodyBgClLbl.Name = "bodyBgClLbl";
			this.bodyBgClLbl.Xalign = 0F;
			this.bodyBgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Body Backcolor");
			this.styleTable.Add (this.bodyBgClLbl);
			global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyBgClLbl]));
			w106.TopAttach = ((uint)(4));
			w106.BottomAttach = ((uint)(5));
			w106.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyBgColorBtn = new global::Gtk.ColorButton ();
			this.bodyBgColorBtn.CanFocus = true;
			this.bodyBgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.bodyBgColorBtn.Name = "bodyBgColorBtn";
			this.styleTable.Add (this.bodyBgColorBtn);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyBgColorBtn]));
			w107.TopAttach = ((uint)(4));
			w107.BottomAttach = ((uint)(5));
			w107.LeftAttach = ((uint)(1));
			w107.RightAttach = ((uint)(2));
			w107.XOptions = ((global::Gtk.AttachOptions)(1));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyFormatScroll = new global::Gtk.ScrolledWindow ();
			this.bodyFormatScroll.Name = "bodyFormatScroll";
			this.bodyFormatScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child bodyFormatScroll.Gtk.Container+ContainerChild
			this.bodyFormatTxt = new global::Gtk.TextView ();
			this.bodyFormatTxt.CanFocus = true;
			this.bodyFormatTxt.Name = "bodyFormatTxt";
			this.bodyFormatScroll.Add (this.bodyFormatTxt);
			this.styleTable.Add (this.bodyFormatScroll);
			global::Gtk.Table.TableChild w109 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyFormatScroll]));
			w109.TopAttach = ((uint)(14));
			w109.BottomAttach = ((uint)(15));
			w109.LeftAttach = ((uint)(1));
			w109.RightAttach = ((uint)(2));
			w109.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.bodyFormatTxLbl = new global::Gtk.Label ();
			this.bodyFormatTxLbl.Name = "bodyFormatTxLbl";
			this.bodyFormatTxLbl.Xalign = 0F;
			this.bodyFormatTxLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Body Format");
			this.styleTable.Add (this.bodyFormatTxLbl);
			global::Gtk.Table.TableChild w110 = ((global::Gtk.Table.TableChild)(this.styleTable [this.bodyFormatTxLbl]));
			w110.TopAttach = ((uint)(14));
			w110.BottomAttach = ((uint)(15));
			w110.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.colorsLbl = new global::Gtk.Label ();
			this.colorsLbl.Name = "colorsLbl";
			this.colorsLbl.Xalign = 0F;
			this.colorsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Colors</b>");
			this.colorsLbl.UseMarkup = true;
			this.styleTable.Add (this.colorsLbl);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.styleTable [this.colorsLbl]));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.detailFnLbl = new global::Gtk.Label ();
			this.detailFnLbl.Name = "detailFnLbl";
			this.detailFnLbl.Xalign = 0F;
			this.detailFnLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Detail Font");
			this.styleTable.Add (this.detailFnLbl);
			global::Gtk.Table.TableChild w112 = ((global::Gtk.Table.TableChild)(this.styleTable [this.detailFnLbl]));
			w112.TopAttach = ((uint)(12));
			w112.BottomAttach = ((uint)(13));
			w112.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.detailFontBtn = new global::Gtk.FontButton ();
			this.detailFontBtn.CanFocus = true;
			this.detailFontBtn.Name = "detailFontBtn";
			this.styleTable.Add (this.detailFontBtn);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.styleTable [this.detailFontBtn]));
			w113.TopAttach = ((uint)(12));
			w113.BottomAttach = ((uint)(13));
			w113.LeftAttach = ((uint)(1));
			w113.RightAttach = ((uint)(2));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.footerBgClLbl = new global::Gtk.Label ();
			this.footerBgClLbl.Name = "footerBgClLbl";
			this.footerBgClLbl.Xalign = 0F;
			this.footerBgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Footer Backcolor");
			this.styleTable.Add (this.footerBgClLbl);
			global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.styleTable [this.footerBgClLbl]));
			w114.TopAttach = ((uint)(5));
			w114.BottomAttach = ((uint)(6));
			w114.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.footerBgColorBtn = new global::Gtk.ColorButton ();
			this.footerBgColorBtn.CanFocus = true;
			this.footerBgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.footerBgColorBtn.Name = "footerBgColorBtn";
			this.styleTable.Add (this.footerBgColorBtn);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.styleTable [this.footerBgColorBtn]));
			w115.TopAttach = ((uint)(5));
			w115.BottomAttach = ((uint)(6));
			w115.LeftAttach = ((uint)(1));
			w115.RightAttach = ((uint)(2));
			w115.XOptions = ((global::Gtk.AttachOptions)(1));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.headerBgClLbl = new global::Gtk.Label ();
			this.headerBgClLbl.Name = "headerBgClLbl";
			this.headerBgClLbl.Xalign = 0F;
			this.headerBgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Header Backcolor");
			this.styleTable.Add (this.headerBgClLbl);
			global::Gtk.Table.TableChild w116 = ((global::Gtk.Table.TableChild)(this.styleTable [this.headerBgClLbl]));
			w116.TopAttach = ((uint)(1));
			w116.BottomAttach = ((uint)(2));
			w116.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.headerBgColorBtn = new global::Gtk.ColorButton ();
			this.headerBgColorBtn.CanFocus = true;
			this.headerBgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.headerBgColorBtn.Name = "headerBgColorBtn";
			this.styleTable.Add (this.headerBgColorBtn);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.styleTable [this.headerBgColorBtn]));
			w117.TopAttach = ((uint)(1));
			w117.BottomAttach = ((uint)(2));
			w117.LeftAttach = ((uint)(1));
			w117.RightAttach = ((uint)(2));
			w117.XOptions = ((global::Gtk.AttachOptions)(1));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconBgColorBtn = new global::Gtk.ColorButton ();
			this.iconBgColorBtn.CanFocus = true;
			this.iconBgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.iconBgColorBtn.Name = "iconBgColorBtn";
			this.styleTable.Add (this.iconBgColorBtn);
			global::Gtk.Table.TableChild w118 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconBgColorBtn]));
			w118.TopAttach = ((uint)(7));
			w118.BottomAttach = ((uint)(8));
			w118.LeftAttach = ((uint)(1));
			w118.RightAttach = ((uint)(2));
			w118.XOptions = ((global::Gtk.AttachOptions)(1));
			w118.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconBgColorLbl = new global::Gtk.Label ();
			this.iconBgColorLbl.Name = "iconBgColorLbl";
			this.iconBgColorLbl.Xalign = 0F;
			this.iconBgColorLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Icon Backcolor");
			this.styleTable.Add (this.iconBgColorLbl);
			global::Gtk.Table.TableChild w119 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconBgColorLbl]));
			w119.TopAttach = ((uint)(7));
			w119.BottomAttach = ((uint)(8));
			w119.XOptions = ((global::Gtk.AttachOptions)(4));
			w119.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconFgColorBtn = new global::Gtk.ColorButton ();
			this.iconFgColorBtn.CanFocus = true;
			this.iconFgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.iconFgColorBtn.Name = "iconFgColorBtn";
			this.styleTable.Add (this.iconFgColorBtn);
			global::Gtk.Table.TableChild w120 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconFgColorBtn]));
			w120.TopAttach = ((uint)(8));
			w120.BottomAttach = ((uint)(9));
			w120.LeftAttach = ((uint)(1));
			w120.RightAttach = ((uint)(2));
			w120.XOptions = ((global::Gtk.AttachOptions)(1));
			w120.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconFgColorLbl = new global::Gtk.Label ();
			this.iconFgColorLbl.Name = "iconFgColorLbl";
			this.iconFgColorLbl.Xalign = 0F;
			this.iconFgColorLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Icon Forecolor");
			this.styleTable.Add (this.iconFgColorLbl);
			global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconFgColorLbl]));
			w121.TopAttach = ((uint)(8));
			w121.BottomAttach = ((uint)(9));
			w121.XOptions = ((global::Gtk.AttachOptions)(4));
			w121.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconFontBtn = new global::Gtk.FontButton ();
			this.iconFontBtn.CanFocus = true;
			this.iconFontBtn.Name = "iconFontBtn";
			this.iconFontBtn.FontName = "Sans 10";
			this.styleTable.Add (this.iconFontBtn);
			global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconFontBtn]));
			w122.TopAttach = ((uint)(13));
			w122.BottomAttach = ((uint)(14));
			w122.LeftAttach = ((uint)(1));
			w122.RightAttach = ((uint)(2));
			w122.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.iconLbl = new global::Gtk.Label ();
			this.iconLbl.Name = "iconLbl";
			this.iconLbl.Xalign = 0F;
			this.iconLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Icon Font");
			this.styleTable.Add (this.iconLbl);
			global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.styleTable [this.iconLbl]));
			w123.TopAttach = ((uint)(13));
			w123.BottomAttach = ((uint)(14));
			w123.XOptions = ((global::Gtk.AttachOptions)(4));
			w123.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.styleSpacer2 = new global::Gtk.Fixed ();
			this.styleSpacer2.HeightRequest = 10;
			this.styleSpacer2.Name = "styleSpacer2";
			this.styleSpacer2.HasWindow = false;
			this.styleTable.Add (this.styleSpacer2);
			global::Gtk.Table.TableChild w124 = ((global::Gtk.Table.TableChild)(this.styleTable [this.styleSpacer2]));
			w124.TopAttach = ((uint)(9));
			w124.BottomAttach = ((uint)(10));
			w124.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.textLbl = new global::Gtk.Label ();
			this.textLbl.Name = "textLbl";
			this.textLbl.Xalign = 0F;
			this.textLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Text</b>");
			this.textLbl.UseMarkup = true;
			this.styleTable.Add (this.textLbl);
			global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.styleTable [this.textLbl]));
			w125.TopAttach = ((uint)(10));
			w125.BottomAttach = ((uint)(11));
			w125.XOptions = ((global::Gtk.AttachOptions)(4));
			w125.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.timeFgClLbl = new global::Gtk.Label ();
			this.timeFgClLbl.Name = "timeFgClLbl";
			this.timeFgClLbl.Xalign = 0F;
			this.timeFgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Timestamp Forecolor");
			this.styleTable.Add (this.timeFgClLbl);
			global::Gtk.Table.TableChild w126 = ((global::Gtk.Table.TableChild)(this.styleTable [this.timeFgClLbl]));
			w126.TopAttach = ((uint)(2));
			w126.BottomAttach = ((uint)(3));
			w126.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.timeFgColorBtn = new global::Gtk.ColorButton ();
			this.timeFgColorBtn.CanFocus = true;
			this.timeFgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.timeFgColorBtn.Name = "timeFgColorBtn";
			this.styleTable.Add (this.timeFgColorBtn);
			global::Gtk.Table.TableChild w127 = ((global::Gtk.Table.TableChild)(this.styleTable [this.timeFgColorBtn]));
			w127.TopAttach = ((uint)(2));
			w127.BottomAttach = ((uint)(3));
			w127.LeftAttach = ((uint)(1));
			w127.RightAttach = ((uint)(2));
			w127.XOptions = ((global::Gtk.AttachOptions)(0));
			w127.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.titleFgClLbl = new global::Gtk.Label ();
			this.titleFgClLbl.Name = "titleFgClLbl";
			this.titleFgClLbl.Xalign = 0F;
			this.titleFgClLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Title Forecolor");
			this.styleTable.Add (this.titleFgClLbl);
			global::Gtk.Table.TableChild w128 = ((global::Gtk.Table.TableChild)(this.styleTable [this.titleFgClLbl]));
			w128.TopAttach = ((uint)(3));
			w128.BottomAttach = ((uint)(4));
			w128.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.titleFgColorBtn = new global::Gtk.ColorButton ();
			this.titleFgColorBtn.CanFocus = true;
			this.titleFgColorBtn.Events = ((global::Gdk.EventMask)(784));
			this.titleFgColorBtn.Name = "titleFgColorBtn";
			this.styleTable.Add (this.titleFgColorBtn);
			global::Gtk.Table.TableChild w129 = ((global::Gtk.Table.TableChild)(this.styleTable [this.titleFgColorBtn]));
			w129.TopAttach = ((uint)(3));
			w129.BottomAttach = ((uint)(4));
			w129.LeftAttach = ((uint)(1));
			w129.RightAttach = ((uint)(2));
			w129.XOptions = ((global::Gtk.AttachOptions)(1));
			w129.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.titleFnLbl = new global::Gtk.Label ();
			this.titleFnLbl.Name = "titleFnLbl";
			this.titleFnLbl.Xalign = 0F;
			this.titleFnLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Title Font");
			this.styleTable.Add (this.titleFnLbl);
			global::Gtk.Table.TableChild w130 = ((global::Gtk.Table.TableChild)(this.styleTable [this.titleFnLbl]));
			w130.TopAttach = ((uint)(11));
			w130.BottomAttach = ((uint)(12));
			w130.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child styleTable.Gtk.Table+TableChild
			this.titleFontBtn = new global::Gtk.FontButton ();
			this.titleFontBtn.CanFocus = true;
			this.titleFontBtn.Name = "titleFontBtn";
			this.styleTable.Add (this.titleFontBtn);
			global::Gtk.Table.TableChild w131 = ((global::Gtk.Table.TableChild)(this.styleTable [this.titleFontBtn]));
			w131.TopAttach = ((uint)(11));
			w131.BottomAttach = ((uint)(12));
			w131.LeftAttach = ((uint)(1));
			w131.RightAttach = ((uint)(2));
			w131.YOptions = ((global::Gtk.AttachOptions)(4));
			this.styleWrapperVbox.Add (this.styleTable);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.styleWrapperVbox [this.styleTable]));
			w132.Position = 1;
			w132.Expand = false;
			w132.Fill = false;
			w96.Add (this.styleWrapperVbox);
			this.styleScroll.Add (w96);
			this.tabControl.Add (this.styleScroll);
			global::Gtk.Notebook.NotebookChild w135 = ((global::Gtk.Notebook.NotebookChild)(this.tabControl [this.styleScroll]));
			w135.Position = 3;
			// Notebook tab
			this.styleSettingsLbl = new global::Gtk.Label ();
			this.styleSettingsLbl.Name = "styleSettingsLbl";
			this.styleSettingsLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Style Settings");
			this.tabControl.SetTabLabel (this.styleScroll, this.styleSettingsLbl);
			this.styleSettingsLbl.ShowAll ();
			w1.Add (this.tabControl);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(w1 [this.tabControl]));
			w136.Position = 0;
			// Internal child CodeWalriiNotify.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w137 = this.ActionArea;
			w137.Name = "dialogActionArea";
			w137.Spacing = 10;
			w137.BorderWidth = ((uint)(5));
			w137.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.CanDefault = true;
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseStock = true;
			this.okButton.UseUnderline = true;
			this.okButton.Label = "gtk-ok";
			this.AddActionWidget (this.okButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w138 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w137 [this.okButton]));
			w138.Expand = false;
			w138.Fill = false;
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanDefault = true;
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseStock = true;
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.cancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w139 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w137 [this.cancelButton]));
			w139.Position = 1;
			w139.Expand = false;
			w139.Fill = false;
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.defaultsButton = new global::Gtk.Button ();
			this.defaultsButton.CanFocus = true;
			this.defaultsButton.Name = "defaultsButton";
			this.defaultsButton.UseUnderline = true;
			this.defaultsButton.Label = global::Mono.Unix.Catalog.GetString ("Load All Defaults");
			this.AddActionWidget (this.defaultsButton, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w140 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w137 [this.defaultsButton]));
			w140.Position = 2;
			w140.Expand = false;
			w140.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 652;
			this.DefaultHeight = 380;
			this.Show ();
			this.generalLoadDefaults.Clicked += new global::System.EventHandler (this.OnGeneralLoadDefaultsClicked);
			this.notificationLoadDefaultsBtn.Clicked += new global::System.EventHandler (this.OnNotificationLoadDefaultsBtnClicked);
			this.contentLoadDefaultsBtn.Clicked += new global::System.EventHandler (this.OnContentLoadDefaultsBtnClicked);
			this.ignUsersAddBtn.Clicked += new global::System.EventHandler (this.OnIgnUsersAddBtnClicked);
			this.ignUsersRemoveBtn.Clicked += new global::System.EventHandler (this.OnIgnUsersRemoveBtnClicked);
			this.ignTopicAddBtn.Clicked += new global::System.EventHandler (this.OnIgnTopicAddBtnClicked);
			this.ignTopicsRemoveBtn.Clicked += new global::System.EventHandler (this.OnIgnTopicsRemoveBtnClicked);
			this.stylesLoadDefaultsBtn.Clicked += new global::System.EventHandler (this.OnStylesLoadDefaultsBtnClicked);
			this.okButton.Clicked += new global::System.EventHandler (this.OnOkButtonClicked);
			this.cancelButton.Clicked += new global::System.EventHandler (this.OnCancelButtonClicked);
			this.defaultsButton.Clicked += new global::System.EventHandler (this.OnDefaultsButtonClicked);
		}
	}
}
