
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class PostWidget
	{
		private global::Gtk.EventBox mainBox;
		
		private global::Gtk.VBox vLayoutBox;
		
		private global::Gtk.EventBox headerBox;
		
		private global::Gtk.Fixed headerContainer;
		
		private global::Gtk.Label timeLabel;
		
		private global::Gtk.Label topicLabel;
		
		private global::Gtk.EventBox bodyBox;
		
		private global::Gtk.Image bodyRenderarea;
		
		private global::Gtk.EventBox footerBox;
		
		private global::Gtk.Fixed footerContainer;
		
		private global::Gtk.Label posterLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.PostWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.PostWidget";
			// Container child CodeWalriiNotify.PostWidget.Gtk.Container+ContainerChild
			this.mainBox = new global::Gtk.EventBox ();
			this.mainBox.Name = "mainBox";
			// Container child mainBox.Gtk.Container+ContainerChild
			this.vLayoutBox = new global::Gtk.VBox ();
			this.vLayoutBox.Name = "vLayoutBox";
			this.vLayoutBox.Spacing = 6;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.headerBox = new global::Gtk.EventBox ();
			this.headerBox.Events = ((global::Gdk.EventMask)(32));
			this.headerBox.Name = "headerBox";
			// Container child headerBox.Gtk.Container+ContainerChild
			this.headerContainer = new global::Gtk.Fixed ();
			this.headerContainer.WidthRequest = 450;
			this.headerContainer.HeightRequest = 75;
			this.headerContainer.Name = "headerContainer";
			this.headerContainer.HasWindow = false;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.timeLabel = new global::Gtk.Label ();
			this.timeLabel.WidthRequest = 300;
			this.timeLabel.HeightRequest = 15;
			this.timeLabel.Name = "timeLabel";
			this.timeLabel.Xalign = 1F;
			this.timeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Time");
			this.headerContainer.Add (this.timeLabel);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.timeLabel]));
			w1.X = 150;
			w1.Y = 53;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.topicLabel = new global::Gtk.Label ();
			this.topicLabel.WidthRequest = 430;
			this.topicLabel.HeightRequest = 30;
			this.topicLabel.Name = "topicLabel";
			this.topicLabel.Xalign = 0F;
			this.topicLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Topic");
			this.topicLabel.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.headerContainer.Add (this.topicLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.topicLabel]));
			w2.X = 10;
			w2.Y = 7;
			this.headerBox.Add (this.headerContainer);
			this.vLayoutBox.Add (this.headerBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.headerBox]));
			w4.Position = 0;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.bodyBox = new global::Gtk.EventBox ();
			this.bodyBox.Name = "bodyBox";
			// Container child bodyBox.Gtk.Container+ContainerChild
			this.bodyRenderarea = new global::Gtk.Image ();
			this.bodyRenderarea.WidthRequest = 440;
			this.bodyRenderarea.HeightRequest = 100;
			this.bodyRenderarea.Name = "bodyRenderarea";
			this.bodyRenderarea.Xpad = 5;
			this.bodyRenderarea.Ypad = 5;
			this.bodyRenderarea.Xalign = 0F;
			this.bodyRenderarea.Yalign = 0F;
			this.bodyBox.Add (this.bodyRenderarea);
			this.vLayoutBox.Add (this.bodyBox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.bodyBox]));
			w6.Position = 1;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.footerBox = new global::Gtk.EventBox ();
			this.footerBox.Name = "footerBox";
			// Container child footerBox.Gtk.Container+ContainerChild
			this.footerContainer = new global::Gtk.Fixed ();
			this.footerContainer.HeightRequest = 20;
			this.footerContainer.Name = "footerContainer";
			this.footerContainer.HasWindow = false;
			// Container child footerContainer.Gtk.Fixed+FixedChild
			this.posterLabel = new global::Gtk.Label ();
			this.posterLabel.WidthRequest = 300;
			this.posterLabel.HeightRequest = 15;
			this.posterLabel.Name = "posterLabel";
			this.posterLabel.Xalign = 1F;
			this.posterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Poster");
			this.footerContainer.Add (this.posterLabel);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.footerContainer [this.posterLabel]));
			w7.X = 150;
			w7.Y = 2;
			this.footerBox.Add (this.footerContainer);
			this.vLayoutBox.Add (this.footerBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.footerBox]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.mainBox.Add (this.vLayoutBox);
			this.Add (this.mainBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
