
// This file has been generated by the GUI designer. Do not modify.
namespace CodeWalriiNotify
{
	public partial class PostWidget
	{
		private global::Gtk.EventBox mainBox;
		
		private global::Gtk.VBox vLayoutBox;
		
		private global::Gtk.EventBox headerBox;
		
		private global::Gtk.Fixed headerContainer;
		
		private global::Gtk.Label topicLabel;
		
		private global::Gtk.Label timeLabel;
		
		private global::Gtk.EventBox bodyBox;
		
		private global::Gtk.Fixed bodyContainer;
		
		private global::Gtk.Label bodyMarkup;
		
		private global::Gtk.Label posterLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CodeWalriiNotify.PostWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CodeWalriiNotify.PostWidget";
			// Container child CodeWalriiNotify.PostWidget.Gtk.Container+ContainerChild
			this.mainBox = new global::Gtk.EventBox ();
			this.mainBox.Name = "mainBox";
			// Container child mainBox.Gtk.Container+ContainerChild
			this.vLayoutBox = new global::Gtk.VBox ();
			this.vLayoutBox.Name = "vLayoutBox";
			this.vLayoutBox.Spacing = 6;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.headerBox = new global::Gtk.EventBox ();
			this.headerBox.Name = "headerBox";
			// Container child headerBox.Gtk.Container+ContainerChild
			this.headerContainer = new global::Gtk.Fixed ();
			this.headerContainer.WidthRequest = 450;
			this.headerContainer.HeightRequest = 75;
			this.headerContainer.Name = "headerContainer";
			this.headerContainer.HasWindow = false;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.topicLabel = new global::Gtk.Label ();
			this.topicLabel.WidthRequest = 430;
			this.topicLabel.HeightRequest = 30;
			this.topicLabel.Name = "topicLabel";
			this.topicLabel.Xalign = 0F;
			this.topicLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Topic");
			this.topicLabel.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.headerContainer.Add (this.topicLabel);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.topicLabel]));
			w1.X = 9;
			w1.Y = 7;
			// Container child headerContainer.Gtk.Fixed+FixedChild
			this.timeLabel = new global::Gtk.Label ();
			this.timeLabel.WidthRequest = 300;
			this.timeLabel.HeightRequest = 15;
			this.timeLabel.Name = "timeLabel";
			this.timeLabel.Xalign = 1F;
			this.timeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Time");
			this.headerContainer.Add (this.timeLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.headerContainer [this.timeLabel]));
			w2.X = 146;
			w2.Y = 53;
			this.headerBox.Add (this.headerContainer);
			this.vLayoutBox.Add (this.headerBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.headerBox]));
			w4.Position = 0;
			// Container child vLayoutBox.Gtk.Box+BoxChild
			this.bodyBox = new global::Gtk.EventBox ();
			this.bodyBox.Name = "bodyBox";
			// Container child bodyBox.Gtk.Container+ContainerChild
			this.bodyContainer = new global::Gtk.Fixed ();
			this.bodyContainer.WidthRequest = 200;
			this.bodyContainer.HeightRequest = 200;
			this.bodyContainer.Name = "bodyContainer";
			this.bodyContainer.HasWindow = false;
			// Container child bodyContainer.Gtk.Fixed+FixedChild
			this.bodyMarkup = new global::Gtk.Label ();
			this.bodyMarkup.WidthRequest = 430;
			this.bodyMarkup.HeightRequest = 150;
			this.bodyMarkup.Name = "bodyMarkup";
			this.bodyMarkup.Xalign = 0F;
			this.bodyMarkup.Yalign = 0F;
			this.bodyMarkup.LabelProp = "BodyMarkup\n\nSo <u>this</u> <i>is</i> some <a href=\"http://codewalr.us/\">working</" +
			"a> <b>markup</b>!";
			this.bodyMarkup.UseMarkup = true;
			this.bodyMarkup.Wrap = true;
			this.bodyMarkup.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.bodyContainer.Add (this.bodyMarkup);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.bodyContainer [this.bodyMarkup]));
			w5.X = 10;
			w5.Y = 11;
			// Container child bodyContainer.Gtk.Fixed+FixedChild
			this.posterLabel = new global::Gtk.Label ();
			this.posterLabel.WidthRequest = 300;
			this.posterLabel.HeightRequest = 15;
			this.posterLabel.Name = "posterLabel";
			this.posterLabel.Xalign = 1F;
			this.posterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Poster");
			this.bodyContainer.Add (this.posterLabel);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.bodyContainer [this.posterLabel]));
			w6.X = 145;
			w6.Y = 177;
			this.bodyBox.Add (this.bodyContainer);
			this.vLayoutBox.Add (this.bodyBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vLayoutBox [this.bodyBox]));
			w8.Position = 1;
			this.mainBox.Add (this.vLayoutBox);
			this.Add (this.mainBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
